---
- name: Ensure prerequisite packages are installed
  ansible.builtin.apt:
    name: "{{ docker_packages[0:4] }}"
    state: present
    update_cache: true

- name: Add Docker’s official GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present

- name: Install Docker packages
  ansible.builtin.apt:
    name: "{{ docker_packages[4:] }}"
    state: present
    update_cache: true

- name: Ensure Docker service is running and enabled
  ansible.builtin.service:
    name: docker
    state: started
    enabled: true

- name: Add ubuntu user to docker group
  ansible.builtin.user:
    name: ubuntu
    groups: docker
    append: yes
